version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-5.6
      - test-7.0
      - test-7.1
      # - test-7.2 # TODO: make our code compatible with PHP 7.2
      - integration-test-5.6

php-docker-template: &php-docker-template
  steps: &php-build-steps
    - checkout
    - run:
        name: install current dependencies
        command: composer install --no-progress
    - run:
        name: run tests with current dependency versions
        command: vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --coverage-text tests
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
    - run:
        name: run tests with highest available dependency versions
        command: composer update --no-progress && vendor/bin/phpunit tests
    - run:
        name: run tests with lowest available dependency versions
        command: composer update --prefer-lowest --no-progress && vendor/bin/phpunit tests

jobs:
  test-5.6:
    <<: *php-docker-template
    docker:
      - image: circleci/php:5.6.34-cli-jessie
  test-7.0:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.0.28-cli-jessie
  test-7.1:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.1.15-cli-jessie
  test-7.2:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.2.3-cli-stretch

  test-5.5: # CircleCI doesn't provide a Docker image for 5.5
    machine:
      - image: circleci/classic:latest # Ubuntu 14.04
    steps:
      <<: *php-build-steps

  integration-test-5.6:
    docker:
      - image: circleci/php:5.6.34-cli-jessie
      - image: redis
    steps:
      - checkout
      - run:
          name: setup apcu
          command: |
            pecl config-set php_ini /usr/local/etc/php/php.ini
            yes '' | sudo pecl install -f apcu-4.0.10 || true;
            echo "extension=apcu.so" | sudo tee -a /usr/local/etc/php/conf.d/apcu.ini;
            echo "apc.enable_cli = 1" | sudo tee -a /usr/local/etc/php/conf.d/apcu.ini
      - run: composer update --no-progress
      - run: vendor/bin/phpunit integration-tests/LDDFeatureRequesterTest.php
