version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-5.6
      - test-7.0
      - test-7.1
      - test-7.2
      - integration-test-5.6

php-docker-template: &test-template
  steps:
    - checkout
    - run:
        name: setup apcu
        command: |
          yes '' | pecl install -f apcu-4.0.10;
          echo "extension=apcu.so" >> $(php-config --prefix)/etc/conf.d/apcu.ini;
          echo "apc.enable_cli = 1" >> $(php-config --prefix)/etc/conf.d/apcu.ini
    - run:
        name: run tests with current dependency versions
        command: vendor/bin/phpunit tests --coverage-text
    - run:
        name: run tests with highest available dependency versions
        command: composer update && vendor/bin/phpunit tests
    - run:
        name: run tests with lowest available dependency versions
        command: composer update --prefer-lowest && vendor/bin/phpunit tests

jobs:
  test-5.6:
    <<: *php-docker-template
    docker:
      - image: circleci/php:5.6.34-cli-jessie
  test-7.0:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.0.28-cli-jessie
  test-7.1:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.1.15-cli-jessie
  test-7.2:
    <<: *php-docker-template
    docker:
      - image: circleci/php:7.2.3-cli-stretch

  integration-test-5.6:
    docker:
      - image: circleci/php:5.6.34-cli-jessie
    steps:
      - checkout
      - run: vendor/bin/phpunit integration-tests/LDDFeatureRequesterTest.php
